# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 'd9d1e589f21c54c5d449fb98728d46c98854cae679738780fe4eb2574c270ab02e748b0775c379417b1d8ed94edd8b4db058970eb475dd2dd6eb0b63c63c99db'
  sidekiq:
    redis_uri: "redis://localhost:6379/1"
  readings:
    redis_uri: "redis://localhost:6379/2"
  locker:
    redis_uri: "redis://localhost:6379/3"

test:
  secret_key_base: '82e70d75ae3c411070a387cd9ea6989420556fee0bbe5b45ee8d91b7047f1c0b2075132715cf5a0cf3ee225873897eb79438470cd4f92156aa60ee02ddbcdf3d'
  readings_manager:
    redis_uri: "redis://localhost:6379/4"
  locker:
    redis_uri: "redis://localhost:6379/5"

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>